/**
 * Catálogo de vitrina para la revisión visual.
 *
 * Usa AppID reales para poder cargar el arte oficial de la CDN pública de
 * Steam durante la captura de pantallas. Sólo se emplea en el escenario
 * `showcase`, que no forma parte de la batería de regresión: el resto de
 * pruebas sigue trabajando sin red y con datos ficticios.
 */

export interface ShowcaseEntry {
  appId: number;
  title: string;
  developer: string;
  publisher: string;
  genres: string[];
  status: "playing" | "finished" | "unclassified" | "backlog" | "paused";
  progress: number;
  priority: number;
  rating?: number;
  playtimeMinutes: number;
  recentMinutes: number;
  installed: boolean;
  pinned?: boolean;
  releaseDate: string;
  lastPlayedAt?: string;
  shortDescription: string;
}

export const SHOWCASE_CATALOG: ShowcaseEntry[] = [
  {
    appId: 1245620,
    title: "ELDEN RING",
    developer: "FromSoftware",
    publisher: "Bandai Namco",
    genres: ["Acción", "Rol"],
    status: "playing",
    progress: 62,
    priority: 5,
    rating: 10,
    playtimeMinutes: 7_412,
    recentMinutes: 640,
    installed: true,
    pinned: true,
    releaseDate: "2022-02-25",
    lastPlayedAt: "2026-08-17T22:40:00Z",
    shortDescription:
      "Un mundo abierto de fantasía oscura donde cada horizonte esconde una ruina que merece la pena rodear.",
  },
  {
    appId: 1091500,
    title: "Cyberpunk 2077",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    genres: ["Rol", "Acción"],
    status: "playing",
    progress: 44,
    priority: 4,
    rating: 9,
    playtimeMinutes: 3_180,
    recentMinutes: 420,
    installed: true,
    releaseDate: "2020-12-10",
    lastPlayedAt: "2026-08-16T23:10:00Z",
    shortDescription: "Night City recompensa la curiosidad lateral tanto como la trama principal.",
  },
  {
    appId: 292030,
    title: "The Witcher 3: Wild Hunt",
    developer: "CD PROJEKT RED",
    publisher: "CD PROJEKT RED",
    genres: ["Rol", "Aventura"],
    status: "finished",
    progress: 100,
    priority: 1,
    rating: 10,
    playtimeMinutes: 9_640,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2015-05-18",
    lastPlayedAt: "2026-04-02T21:00:00Z",
    shortDescription:
      "Contratos secundarios escritos con más cuidado que las campañas principales de casi todo lo demás.",
  },
  {
    appId: 1145360,
    title: "Hades",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genres: ["Acción", "Roguelike"],
    status: "finished",
    progress: 100,
    priority: 2,
    rating: 10,
    playtimeMinutes: 4_120,
    recentMinutes: 120,
    installed: true,
    releaseDate: "2020-09-17",
    lastPlayedAt: "2026-08-10T19:30:00Z",
    shortDescription: "El bucle de muerte y regreso mejor escrito del género.",
  },
  {
    appId: 367520,
    title: "Hollow Knight",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    genres: ["Metroidvania", "Plataformas"],
    status: "playing",
    progress: 78,
    priority: 4,
    rating: 10,
    playtimeMinutes: 2_890,
    recentMinutes: 260,
    installed: true,
    releaseDate: "2017-02-24",
    lastPlayedAt: "2026-08-15T20:05:00Z",
    shortDescription: "Hallownest se explora sin mapa y se recuerda para siempre.",
  },
  {
    appId: 413150,
    title: "Stardew Valley",
    developer: "ConcernedApe",
    publisher: "ConcernedApe",
    genres: ["Simulación", "Rol"],
    status: "paused",
    progress: 55,
    priority: 2,
    rating: 9,
    playtimeMinutes: 5_620,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2016-02-26",
    lastPlayedAt: "2026-02-18T18:20:00Z",
    shortDescription: "Un año agrícola completo cabe en un puñado de tardes.",
  },
  {
    appId: 620,
    title: "Portal 2",
    developer: "Valve",
    publisher: "Valve",
    genres: ["Puzles", "Aventura"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 10,
    playtimeMinutes: 720,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2011-04-18",
    lastPlayedAt: "2025-11-03T22:15:00Z",
    shortDescription:
      "La lección permanente sobre cómo enseñar una mecánica sin decir una palabra.",
  },
  {
    appId: 553850,
    title: "HELLDIVERS 2",
    developer: "Arrowhead Game Studios",
    publisher: "PlayStation Publishing",
    genres: ["Acción", "Cooperativo"],
    status: "playing",
    progress: 30,
    priority: 3,
    rating: 8,
    playtimeMinutes: 1_960,
    recentMinutes: 380,
    installed: true,
    releaseDate: "2024-02-08",
    lastPlayedAt: "2026-08-17T00:30:00Z",
    shortDescription: "La democracia gestionada exige coordinación real con tres amigos.",
  },
  {
    appId: 1174180,
    title: "Red Dead Redemption 2",
    developer: "Rockstar Games",
    publisher: "Rockstar Games",
    genres: ["Aventura", "Acción"],
    status: "backlog",
    progress: 8,
    priority: 3,
    playtimeMinutes: 340,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2019-12-05",
    shortDescription: "Un western que pide paciencia antes de devolver nada.",
  },
  {
    appId: 105600,
    title: "Terraria",
    developer: "Re-Logic",
    publisher: "Re-Logic",
    genres: ["Aventura", "Sandbox"],
    status: "paused",
    progress: 41,
    priority: 1,
    rating: 9,
    playtimeMinutes: 3_240,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2011-05-16",
    lastPlayedAt: "2026-01-09T17:45:00Z",
    shortDescription: "Excavar hacia abajo sigue siendo una decisión con consecuencias.",
  },
  {
    appId: 646570,
    title: "Slay the Spire",
    developer: "Mega Crit Games",
    publisher: "Mega Crit Games",
    genres: ["Cartas", "Roguelike"],
    status: "playing",
    progress: 66,
    priority: 3,
    rating: 9,
    playtimeMinutes: 2_410,
    recentMinutes: 180,
    installed: true,
    releaseDate: "2019-01-23",
    lastPlayedAt: "2026-08-14T23:55:00Z",
    shortDescription: "Cada mazo construido es una tesis que la ascensión siguiente refuta.",
  },
  {
    appId: 588650,
    title: "Dead Cells",
    developer: "Motion Twin",
    publisher: "Motion Twin",
    genres: ["Acción", "Roguelike"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 9,
    playtimeMinutes: 1_780,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2018-08-07",
    lastPlayedAt: "2025-09-21T20:10:00Z",
    shortDescription: "Movimiento tan limpio que perder deja de doler.",
  },
  {
    appId: 275850,
    title: "No Man's Sky",
    developer: "Hello Games",
    publisher: "Hello Games",
    genres: ["Aventura", "Supervivencia"],
    status: "backlog",
    progress: 14,
    priority: 2,
    playtimeMinutes: 620,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2016-08-12",
    shortDescription: "Diez años de actualizaciones convirtieron la promesa en catálogo.",
  },
  {
    appId: 322330,
    title: "Don't Starve Together",
    developer: "Klei Entertainment",
    publisher: "Klei Entertainment",
    genres: ["Supervivencia", "Cooperativo"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 180,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2016-04-21",
    shortDescription: "Sobrevivir al primer invierno es el verdadero tutorial.",
  },
  {
    appId: 262060,
    title: "Darkest Dungeon",
    developer: "Red Hook Studios",
    publisher: "Red Hook Studios",
    genres: ["Rol", "Estrategia"],
    status: "paused",
    progress: 37,
    priority: 1,
    rating: 8,
    playtimeMinutes: 1_140,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2016-01-19",
    lastPlayedAt: "2026-03-30T22:00:00Z",
    shortDescription: "El estrés de los héroes es el recurso que de verdad se administra.",
  },
  {
    appId: 1086940,
    title: "Baldur's Gate 3",
    developer: "Larian Studios",
    publisher: "Larian Studios",
    genres: ["Rol", "Estrategia"],
    status: "playing",
    progress: 52,
    priority: 5,
    rating: 10,
    playtimeMinutes: 6_150,
    recentMinutes: 520,
    installed: true,
    pinned: true,
    releaseDate: "2023-08-03",
    lastPlayedAt: "2026-08-17T21:15:00Z",
    shortDescription:
      "Un sistema que responde a casi cualquier idea disparatada que se le plantee.",
  },
  {
    appId: 1817070,
    title: "Marvel's Spider-Man Remastered",
    developer: "Insomniac Games",
    publisher: "PlayStation Publishing",
    genres: ["Acción", "Aventura"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 8,
    playtimeMinutes: 1_320,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-08-12",
    lastPlayedAt: "2025-12-28T19:40:00Z",
    shortDescription: "El desplazamiento por Manhattan justifica el juego entero.",
  },
  {
    appId: 1030300,
    title: "Hollow Knight: Silksong",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    genres: ["Metroidvania", "Plataformas"],
    status: "backlog",
    progress: 0,
    priority: 4,
    playtimeMinutes: 0,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2025-09-04",
    shortDescription: "Hornet cambia el ritmo del original por algo más agresivo.",
  },
  {
    appId: 1237970,
    title: "Titanfall 2",
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    genres: ["Acción", "Disparos"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 9,
    playtimeMinutes: 480,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2020-06-18",
    lastPlayedAt: "2025-08-14T21:00:00Z",
    shortDescription: "Seis horas de campaña sin una sola idea repetida.",
  },
  {
    appId: 8930,
    title: "Sid Meier's Civilization V",
    developer: "Firaxis Games",
    publisher: "2K",
    genres: ["Estrategia", "Por turnos"],
    status: "paused",
    progress: 60,
    priority: 1,
    rating: 8,
    playtimeMinutes: 8_920,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2010-09-21",
    lastPlayedAt: "2026-05-12T02:30:00Z",
    shortDescription: "Un turno más sigue siendo la mentira más cara del catálogo.",
  },
  {
    appId: 1938090,
    title: "Call of Duty",
    developer: "Infinity Ward",
    publisher: "Activision",
    genres: ["Disparos", "Acción"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 90,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-10-28",
    shortDescription: "Entró en la biblioteca por una oferta y ahí sigue.",
  },
  {
    appId: 1966720,
    title: "Lethal Company",
    developer: "Zeekerss",
    publisher: "Zeekerss",
    genres: ["Terror", "Cooperativo"],
    status: "playing",
    progress: 25,
    priority: 2,
    rating: 8,
    playtimeMinutes: 740,
    recentMinutes: 210,
    installed: true,
    releaseDate: "2023-10-23",
    lastPlayedAt: "2026-08-16T01:20:00Z",
    shortDescription: "El miedo se reparte mejor entre cuatro.",
  },
  {
    appId: 1174370,
    title: "STAR WARS Jedi: Fallen Order",
    developer: "Respawn Entertainment",
    publisher: "Electronic Arts",
    genres: ["Acción", "Aventura"],
    status: "backlog",
    progress: 18,
    priority: 2,
    playtimeMinutes: 420,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2020-06-18",
    shortDescription: "Metroidvania con sable, más medido de lo que aparenta.",
  },
  {
    appId: 1593500,
    title: "God of War",
    developer: "Santa Monica Studio",
    publisher: "PlayStation Publishing",
    genres: ["Acción", "Aventura"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 9,
    playtimeMinutes: 1_680,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-01-14",
    lastPlayedAt: "2026-01-30T23:20:00Z",
    shortDescription: "Una sola toma de cámara sostenida durante veinticinco horas.",
  },
  {
    appId: 1332010,
    title: "Stray",
    developer: "BlueTwelve Studio",
    publisher: "Annapurna Interactive",
    genres: ["Aventura", "Puzles"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 8,
    playtimeMinutes: 380,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-07-19",
    lastPlayedAt: "2025-10-11T20:45:00Z",
    shortDescription: "Una tarde entera justificada por la dirección artística.",
  },
  {
    appId: 1794680,
    title: "Vampire Survivors",
    developer: "poncle",
    publisher: "poncle",
    genres: ["Acción", "Roguelike"],
    status: "paused",
    progress: 72,
    priority: 1,
    rating: 8,
    playtimeMinutes: 1_260,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2022-10-20",
    lastPlayedAt: "2026-06-02T18:00:00Z",
    shortDescription: "Veinte minutos por partida que nunca son veinte minutos.",
  },
  {
    appId: 1621690,
    title: "Cult of the Lamb",
    developer: "Massive Monster",
    publisher: "Devolver Digital",
    genres: ["Acción", "Simulación"],
    status: "backlog",
    progress: 22,
    priority: 2,
    playtimeMinutes: 540,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-08-11",
    shortDescription: "Gestión de secta y mazmorras que se alimentan mutuamente.",
  },
  {
    appId: 1145350,
    title: "Hades II",
    developer: "Supergiant Games",
    publisher: "Supergiant Games",
    genres: ["Acción", "Roguelike"],
    status: "playing",
    progress: 34,
    priority: 4,
    rating: 9,
    playtimeMinutes: 980,
    recentMinutes: 340,
    installed: true,
    releaseDate: "2024-05-06",
    lastPlayedAt: "2026-08-17T19:50:00Z",
    shortDescription: "Melinoë hereda el ritmo y añade una capa de recursos.",
  },
  {
    appId: 244850,
    title: "Space Engineers",
    developer: "Keen Software House",
    publisher: "Keen Software House",
    genres: ["Simulación", "Sandbox"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 60,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2019-02-28",
    shortDescription: "Construir una nave y verla desmontarse es media diversión.",
  },
  {
    appId: 730,
    title: "Counter-Strike 2",
    developer: "Valve",
    publisher: "Valve",
    genres: ["Disparos", "Competitivo"],
    status: "paused",
    progress: 0,
    priority: 1,
    rating: 7,
    playtimeMinutes: 12_400,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2012-08-21",
    lastPlayedAt: "2026-07-08T22:10:00Z",
    shortDescription: "La biblioteca entera vive a la sombra de estas horas.",
  },
  {
    appId: 1250410,
    title: "Microsoft Flight Simulator",
    developer: "Asobo Studio",
    publisher: "Xbox Game Studios",
    genres: ["Simulación"],
    status: "backlog",
    progress: 5,
    priority: 1,
    playtimeMinutes: 240,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2021-07-27",
    shortDescription: "El planeta completo como escenario, y ni una hora de vuelo real.",
  },
  {
    appId: 1517290,
    title: "Battlefield 2042",
    developer: "DICE",
    publisher: "Electronic Arts",
    genres: ["Disparos"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 45,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2021-11-19",
    shortDescription: "Sin clasificar desde el día de la compra.",
  },
  {
    appId: 1222670,
    title: "The Sims 4",
    developer: "Maxis",
    publisher: "Electronic Arts",
    genres: ["Simulación"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 120,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2019-06-18",
    shortDescription: "Un catálogo de expansiones más largo que la partida.",
  },
  {
    appId: 292730,
    title: "Sunless Sea",
    developer: "Failbetter Games",
    publisher: "Failbetter Games",
    genres: ["Rol", "Exploración"],
    status: "paused",
    progress: 29,
    priority: 1,
    rating: 8,
    playtimeMinutes: 460,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2015-02-06",
    lastPlayedAt: "2025-07-19T21:30:00Z",
    shortDescription: "Prosa densa y hambre real: se avanza leyendo.",
  },
  {
    appId: 219740,
    title: "Don't Starve",
    developer: "Klei Entertainment",
    publisher: "Klei Entertainment",
    genres: ["Supervivencia"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 8,
    playtimeMinutes: 820,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2013-04-23",
    lastPlayedAt: "2025-06-05T20:00:00Z",
    shortDescription: "El original todavía castiga mejor que su versión cooperativa.",
  },
  {
    appId: 391540,
    title: "Undertale",
    developer: "tobyfox",
    publisher: "tobyfox",
    genres: ["Rol", "Aventura"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 10,
    playtimeMinutes: 390,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2015-09-15",
    lastPlayedAt: "2025-05-22T23:00:00Z",
    shortDescription: "Seis horas que recolocan lo que se espera de un menú de combate.",
  },
  {
    appId: 268910,
    title: "Cuphead",
    developer: "Studio MDHR",
    publisher: "Studio MDHR",
    genres: ["Acción", "Plataformas"],
    status: "backlog",
    progress: 33,
    priority: 2,
    playtimeMinutes: 310,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2017-09-29",
    shortDescription: "Animación cuadro a cuadro y una curva que no perdona.",
  },
  {
    appId: 526870,
    title: "Satisfactory",
    developer: "Coffee Stain Studios",
    publisher: "Coffee Stain Publishing",
    genres: ["Simulación", "Sandbox"],
    status: "playing",
    progress: 48,
    priority: 3,
    rating: 9,
    playtimeMinutes: 2_260,
    recentMinutes: 290,
    installed: true,
    releaseDate: "2024-09-10",
    lastPlayedAt: "2026-08-15T02:00:00Z",
    shortDescription: "Una cinta transportadora mal puesta cuesta tres horas de rediseño.",
  },
  {
    appId: 427520,
    title: "Factorio",
    developer: "Wube Software",
    publisher: "Wube Software",
    genres: ["Simulación", "Estrategia"],
    status: "paused",
    progress: 58,
    priority: 2,
    rating: 10,
    playtimeMinutes: 3_840,
    recentMinutes: 0,
    installed: true,
    releaseDate: "2020-08-14",
    lastPlayedAt: "2026-04-27T04:15:00Z",
    shortDescription: "La fábrica debe crecer, y crecerá a costa del sueño.",
  },
  {
    appId: 1687950,
    title: "Persona 5 Royal",
    developer: "ATLUS",
    publisher: "SEGA",
    genres: ["Rol", "Por turnos"],
    status: "backlog",
    progress: 11,
    priority: 3,
    playtimeMinutes: 620,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-10-21",
    shortDescription: "Cien horas esperando el hueco que nunca aparece.",
  },
  {
    appId: 1449850,
    title: "Yu-Gi-Oh! Master Duel",
    developer: "KONAMI",
    publisher: "KONAMI",
    genres: ["Cartas", "Competitivo"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 30,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-01-19",
    shortDescription: "Descargado por curiosidad y nunca clasificado.",
  },
  {
    appId: 1284190,
    title: "Sifu",
    developer: "Sloclap",
    publisher: "Sloclap",
    genres: ["Acción"],
    status: "backlog",
    progress: 26,
    priority: 2,
    playtimeMinutes: 280,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-03-28",
    shortDescription: "Envejecer con cada muerte convierte el reintento en decisión.",
  },
  {
    appId: 1029210,
    title: "Chained Echoes",
    developer: "Matthias Linda",
    publisher: "Deck13",
    genres: ["Rol", "Por turnos"],
    status: "playing",
    progress: 40,
    priority: 3,
    rating: 9,
    playtimeMinutes: 890,
    recentMinutes: 150,
    installed: true,
    releaseDate: "2022-12-08",
    lastPlayedAt: "2026-08-13T21:40:00Z",
    shortDescription:
      "Un rol clásico escrito por una sola persona y mejor equilibrado que muchos de estudio.",
  },
  {
    appId: 1449690,
    title: "TUNIC",
    developer: "TUNIC Team",
    publisher: "Finji",
    genres: ["Aventura", "Puzles"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 9,
    playtimeMinutes: 720,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2022-03-16",
    lastPlayedAt: "2026-02-11T22:30:00Z",
    shortDescription: "El manual del juego es el propio juego.",
  },
  {
    appId: 1057090,
    title: "Ori and the Will of the Wisps",
    developer: "Moon Studios",
    publisher: "Xbox Game Studios",
    genres: ["Metroidvania", "Plataformas"],
    status: "finished",
    progress: 100,
    priority: 0,
    rating: 9,
    playtimeMinutes: 640,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2020-03-11",
    lastPlayedAt: "2025-11-19T20:20:00Z",
    shortDescription: "Movimiento y música empujando en la misma dirección.",
  },
  {
    appId: 1868140,
    title: "DAVE THE DIVER",
    developer: "MINTROCKET",
    publisher: "MINTROCKET",
    genres: ["Aventura", "Simulación"],
    status: "playing",
    progress: 57,
    priority: 2,
    rating: 8,
    playtimeMinutes: 1_040,
    recentMinutes: 200,
    installed: true,
    releaseDate: "2023-06-28",
    lastPlayedAt: "2026-08-12T20:50:00Z",
    shortDescription:
      "Bucear de día y llevar un restaurante de noche no debería funcionar tan bien.",
  },
  {
    appId: 1382330,
    title: "Persona 4 Golden",
    developer: "ATLUS",
    publisher: "SEGA",
    genres: ["Rol"],
    status: "backlog",
    progress: 3,
    priority: 1,
    playtimeMinutes: 90,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2020-06-13",
    shortDescription: "Empezado dos veces y abandonado dos veces en abril.",
  },
  {
    appId: 1782210,
    title: "Crab Champions",
    developer: "Noisestorm",
    publisher: "Noisestorm",
    genres: ["Disparos", "Roguelike"],
    status: "unclassified",
    progress: 0,
    priority: 0,
    playtimeMinutes: 20,
    recentMinutes: 0,
    installed: false,
    releaseDate: "2023-04-31",
    shortDescription: "Sigue sin encontrar su hueco en ninguna colección.",
  },
];

/** Portada vertical oficial en la máxima resolución que publica la tienda. */
export function showcaseCoverUrl(appId: number): string {
  return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/library_600x900_2x.jpg`;
}

/** Banner apaisado oficial usado por la ficha inmersiva. */
export function showcaseHeroUrl(appId: number): string {
  return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/library_hero.jpg`;
}

/** Cabecera horizontal oficial, respaldo del banner. */
export function showcaseHeaderUrl(appId: number): string {
  return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;
}
